DROP TABLE IF EXISTS t_gender;
CREATE TABLE IF NOT EXISTS `t_gender`(
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '表主键',

  `gender` VARCHAR(64) UNIQUE NOT NULL COMMENT '性别'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='性别' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS t_class_name;
CREATE TABLE IF NOT EXISTS `t_class_name`(
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '表主键',

  `class_name` VARCHAR(64) UNIQUE NOT NULL COMMENT '班级名称'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='班级' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS t_grade;
CREATE TABLE IF NOT EXISTS `t_grade`(
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '表主键',

  `grade` VARCHAR(64) UNIQUE NOT NULL COMMENT '年级'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='年级' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS t_scholarship;
CREATE TABLE IF NOT EXISTS `t_scholarship`(
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '表主键',

  `scholarship_level` INT UNIQUE NOT NULL COMMENT '奖学金等级',
  `money` DECIMAL(10,2) NOT NULL COMMENT '奖学金数目'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='奖学金' AUTO_INCREMENT=1;